name = "coretaxdownload"
main = "worker.js" # Nama file Worker utama (lihat langkah selanjutnya)
compatibility_date = "2025-12-26"

[site]
# Mengarahkan ke root folder proyek (tempat index.html berada)
bucket = "./"
